name: music_cataloger
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  file_selector: ^0.9.3
  metadata_god: ^0.4.1
  rxdart: ^0.27.7
  collection: ^1.17.0
  io: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

